# : Manager {{{

[manager]
cwd = { fg = "cyan" } # Blue

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "red", bold = true, italic = true, underline = true }       # Red
find_position = { fg = "lightmagenta", bg = "reset", bold = true, italic = true } # Magenta

# Marker
marker_copied = { fg = "green", bg = "green" }     # Green
marker_cut = { fg = "yellow", bg = "red" }         # Red
marker_marked = { fg = "magenta", bg = "cyan" }    # Cyan
marker_selected = { fg = "yellow", bg = "yellow" } # Yellow

# Tab
tab_active = { bg = "black", fg = "blue" } # Darkened background, Blue text
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "darkgray", bg = "lightgreen" } # Darkened black on Green
count_cut = { fg = "darkgray", bg = "yellow" }        # Darkened black on Yellow
count_selected = { fg = "darkgray", bg = "blue" }     # Darkened black on Blue

# Border
border_symbol = "│"
border_style = { fg = "#1f2e59" } # Darkened black

# : }}}


# : Select {{{

[select]
border = { fg = "blue" }                 # Blue
active = { fg = "magenta", bold = true } # Magenta
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "blue" }       # Blue
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "blue" } # Blue

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "blue" }                       # Blue
title = {}
hovered = { fg = "magenta", underline = true } # Magenta

# : }}}
# : Which {{{

[which]
mask = { bg = "black" }            # Darkened black
cand = { fg = "green" }            # Green
rest = { fg = "gray" }             # White
desc = { fg = "magenta" }          # Magenta
separator = "  "
separator_style = { fg = "black" } # Darkened gray

# : }}}


# : Help {{{

[help]
on = { fg = "green" }                      # Green
run = { fg = "magenta" }                   # Magenta
hovered = { reversed = true, bold = true }
footer = { fg = "gray", bg = "white" }     # White on Light gray

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "green" }    # Green
title_warn = { fg = "lightred" } # Red
title_error = { fg = "yellow" }  # Yellow

# : }}}
